### ISSUE TITLE
[draft] proposal for specifying receivers for different services

### ISSUE THREAD

**Issue by Gerrrr** [Gerrrr/consul-alerts#1]
As discussed in https://github.com/AcalephStorage/consul-alerts/issues/145, currently it is only possible to specify one list of receives for all the email notifications. In our case it is required to have different receivers for different services.

In order not to break the existing API, I propose to introduce the following parameters to the email notifier:
* `notification-groups` - a map, where keys are group names and values are lists of strings containing emails. It should be possible to use these groups also in the `receivers` parameter.
* `service-receivers` - a map, where keys are regular expressions used to filter services and values are lists of strings containing emails or notification groups

If both `receivers` and `service-receivers` are specified, they should be merged together.

@frosner what do you think?

**Comment by FRosner** [comment]
I think you should not introduce this on a notifier level but instead of the `notification-groups` property on a higher level. It should be a map from service regexes to notifiers and there should be the possibility to have multiple notifiers of each type.

**Comment by Gerrrr** [comment]
@FRosner agree, this way it is cleaner.
Changes in the API:

### Named notifiers of a specific type

Currently, it is only possible to have 1 configuration for 1 notifier type, e.g. `consul-alerts/config/notifiers/email`.

With multiple configurations, it will be possible to send emails to different receivers or post to different slack channels. API example:

* `consul-alerts/config/notifiers/emails/<email-notifier-name>` - a place to keep named notifiers of type emails
* `consul-alerts/config/notifiers/slacks/< slack-notifier-name>` - a place to keep named notifiers of type slack

Then, in the notification profiles it should be possible not only to turn on/off the notifier, but also specify a notifier name:

```
{
  "Interval": 10,
  "NotifList": {
    "log":false,
    "emails": ["team2", "team-3"]
  }
}
```

### Notification Profile Activation using regular expressions

Currently, for every service, check or host to be notified about, there should be a record in `consul-alerts/config/notif-selection/[services|nodes|checks]/` directories. However, It is not possible to configure not just one service, but a group of services. To solve this, we can use `consul-alerts/config/notif-selection/[services|nodes|checks]` keys for the json, mapping groups of services (matched by regexp) to a list of notification profiles. Example:

Key: `consul-alerts/config/notif-selection/services`
Value: 
```json
{
  "^team-1-.*$": ["profile-1", "profile-2"]
}
```
